#!/bin/bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
  echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
  echo -e "${RED}✗${NC} $1"
}

# Check for Supabase CLI
check_supabase_cli() {
  log_info "Checking for Supabase CLI..."

  if ! command -v supabase &> /dev/null; then
    log_warning "Supabase CLI not found. Installing..."

    if [[ "$OSTYPE" == "darwin"* ]]; then
      # macOS
      brew install supabase/tap/supabase
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
      # Linux
      curl -fsSL https://cli.supabase.io/install.sh | bash
    else
      log_error "Unsupported OS. Please install Supabase CLI manually from https://supabase.com/docs/guides/cli/getting-started"
      return 1
    fi
  fi

  log_success "Supabase CLI is installed"
}

# Get Supabase configuration
get_supabase_config() {
  log_info "Getting Supabase configuration..."

  # Try to get from environment variables first
  if [[ -z "${SUPABASE_PROJECT_REF:-}" ]]; then
    read -p "Enter SUPABASE_PROJECT_REF: " SUPABASE_PROJECT_REF
  fi

  if [[ -z "${SUPABASE_DB_PASSWORD:-}" ]]; then
    read -sp "Enter SUPABASE_DB_PASSWORD: " SUPABASE_DB_PASSWORD
    echo
  fi

  if [[ -z "$SUPABASE_PROJECT_REF" ]] || [[ -z "$SUPABASE_DB_PASSWORD" ]]; then
    log_error "Missing Supabase configuration"
    return 1
  fi

  log_success "Supabase configuration loaded"
}

# Run migrations
run_migrations() {
  log_info "Running database migrations..."

  local migrations_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/supabase/migrations"

  if [[ ! -d "$migrations_dir" ]]; then
    log_error "Migrations directory not found: $migrations_dir"
    return 1
  fi

  local migration_files=(
    "${migrations_dir}/001_initial_schema.sql"
    "${migrations_dir}/002_seed_data.sql"
    "${migrations_dir}/003_functions.sql"
    "${migrations_dir}/004_realtime.sql"
    "${migrations_dir}/005_storage.sql"
  )

  for migration_file in "${migration_files[@]}"; do
    if [[ ! -f "$migration_file" ]]; then
      log_error "Migration file not found: $migration_file"
      return 1
    fi

    local migration_name=$(basename "$migration_file")
    log_info "Running migration: $migration_name"

    supabase db push --project-ref "$SUPABASE_PROJECT_REF" --file "$migration_file" || {
      log_error "Migration failed: $migration_name"
      return 1
    }

    log_success "Completed: $migration_name"
  done
}

# Deploy edge functions
deploy_edge_functions() {
  log_info "Deploying edge functions..."

  local functions_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/supabase/functions"
  local functions=(
    "agent-task"
    "approve-action"
    "lead-intake"
    "booking-webhook"
    "analytics"
  )

  for func in "${functions[@]}"; do
    local func_path="${functions_dir}/${func}"

    if [[ ! -d "$func_path" ]]; then
      log_warning "Function directory not found, skipping: $func"
      continue
    fi

    log_info "Deploying function: $func"

    supabase functions deploy "$func" --project-ref "$SUPABASE_PROJECT_REF" || {
      log_error "Failed to deploy function: $func"
      return 1
    }

    log_success "Deployed: $func"
  done
}

# Create .env.local file
create_env_file() {
  log_info "Creating .env.local file..."

  local env_file="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env.local"

  # Get VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY from Supabase
  log_info "Fetching Supabase credentials..."

  # Note: These are placeholders and should be filled in manually or via Supabase API
  cat > "$env_file" << EOF
# Supabase Configuration (generated by setup-supabase.sh)
VITE_SUPABASE_URL=https://${SUPABASE_PROJECT_REF}.supabase.co
VITE_SUPABASE_ANON_KEY=<Replace with your anon key from Supabase dashboard>
SUPABASE_SERVICE_ROLE_KEY=<Replace with your service role key from Supabase dashboard>

# Database
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}

# Vercel (optional for local development)
VERCEL_TOKEN=<optional: for Vercel deployments>
VERCEL_SCOPE=<optional: your Vercel scope>
EOF

  log_success "Created .env.local file: $env_file"
  log_warning "Please update the placeholder values in .env.local with your actual Supabase credentials"
}

# Print success summary
print_summary() {
  echo ""
  echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}✓ Supabase Setup Complete!${NC}"
  echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
  echo ""
  echo "Next steps:"
  echo "1. Update your .env.local file with credentials from Supabase dashboard:"
  echo "   - VITE_SUPABASE_URL (should be pre-filled)"
  echo "   - VITE_SUPABASE_ANON_KEY"
  echo "   - SUPABASE_SERVICE_ROLE_KEY"
  echo ""
  echo "2. Verify migrations ran successfully:"
  echo "   supabase db show --project-ref $SUPABASE_PROJECT_REF"
  echo ""
  echo "3. Test edge functions:"
  echo "   supabase functions list --project-ref $SUPABASE_PROJECT_REF"
  echo ""
  echo "4. Start development:"
  echo "   npm run dev"
  echo ""
  echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
  echo ""
}

# Main execution
main() {
  echo ""
  echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}Supabase Setup Script${NC}"
  echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
  echo ""

  check_supabase_cli || exit 1
  get_supabase_config || exit 1
  run_migrations || exit 1
  deploy_edge_functions || exit 1
  create_env_file || exit 1
  print_summary
}

main "$@"
